[package]
name = "test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rust-scope"
path = "src/main.rs"

[dependencies]
regex = "1.5.4"
glob = "0.3.0"
lazy_static = "1.4.0"
serde_json = "1.0.111"